spring.datasource.url=jdbc:postgresql://dpg-d7o4c2u8bjmc7396r7f0-a.oregon-postgres.render.com:5432/caravan_db_xlvv
spring.datasource.username=caravan_db_xlvv_user
spring.datasource.password=wQ1QpzhHe6CUPPnncnvg5PHOYKEgj9OW

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update